# Generated by Django 5.0.2 on 2024-02-23 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parfum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('familie_olfactiva', models.CharField(choices=[('floral', 'Floral'), ('citrus', 'Citric'), ('lemnos', 'Lemnos'), ('oriental', 'Oriental'), ('proaspat', 'Proaspat')], max_length=50)),
                ('descriere', models.CharField(blank=True, max_length=1500)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('pret', models.FloatField(default=59.99)),
                ('imagine', models.ImageField(upload_to='imagini_parfumuri/')),
            ],
            options={
                'verbose_name_plural': 'parfumuri',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('suma_platita', models.FloatField(null=True)),
                ('adresa_livrare', models.TextField(max_length=1000, null=True)),
                ('telefon', models.IntegerField(null=True)),
                ('data_comenzii', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElementComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.comanda')),
                ('utilizator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parfum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.parfum')),
            ],
        ),
    ]
