# Generated by Django 5.0.2 on 2024-03-06 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('floral', 'Floral'), ('citrus', 'Citric'), ('lemnos', 'Lemnos'), ('oriental', 'Oriental'), ('proaspat', 'Proaspat')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('price', models.FloatField(default=29.99)),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'perfums',
            },
        ),
        migrations.RemoveField(
            model_name='elementcomanda',
            name='comanda',
        ),
        migrations.RemoveField(
            model_name='elementcomanda',
            name='parfum',
        ),
        migrations.RemoveField(
            model_name='elementcomanda',
            name='utilizator',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('amount_paid', models.FloatField(null=True)),
                ('shipping_address', models.TextField(max_length=1000, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.perfum')),
            ],
        ),
        migrations.DeleteModel(
            name='Comanda',
        ),
        migrations.DeleteModel(
            name='Parfum',
        ),
        migrations.DeleteModel(
            name='ElementComanda',
        ),
    ]
