# Generated by Django 5.0.2 on 2024-03-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_perfum_remove_elementcomanda_comanda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfum',
            name='category',
            field=models.CharField(choices=[('floral', 'Floral'), ('citric', 'Citric'), ('lemnos', 'Lemnos'), ('oriental', 'Oriental'), ('proaspat', 'Proaspat')], max_length=50),
        ),
    ]
