# Generated by Django 4.2.7 on 2024-03-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_title_perfum_name_remove_perfum_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parfum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('floral', 'Floral'), ('citric', 'Citric'), ('lemnos', 'Lemnos'), ('oriental', 'Oriental'), ('proaspat', 'Proaspat')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.FloatField(default=59.99)),
            ],
            options={
                'verbose_name_plural': 'perfums',
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.parfum'),
        ),
        migrations.DeleteModel(
            name='Perfum',
        ),
    ]
