# Generated by Django 5.0.6 on 2024-05-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_parfum_alter_orderitem_book_delete_perfum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='book',
            new_name='perfum',
        ),
        migrations.RemoveField(
            model_name='parfum',
            name='category',
        ),
    ]
